import type { AircraftSpec } from './types';

export const CATALOG: AircraftSpec[] = [
  {
    id: 'skylark',
    name: 'SKYLARK ST-2',
    reg: 'N271SL',
    role: 'Light Trainer',
    blurb:
      'The friendly one. A high-wing club trainer that telegraphs every stall and forgives every ham-fisted flare. Slow, honest, and the best seat in the house for sightseeing the archipelago.',
    engine: 'prop',
    stats: { speed: 0.25, agility: 0.35, handling: 0.95, climb: 0.3 },
    topSpeedKt: 145,
    mass: 1080,
    wingArea: 16.2,
    aspect: 7.4,
    cl0: 0.32,
    clSlope: 5.1,
    stallAoA: 0.28,
    cd0: 0.032,
    maxThrust: 4200,
    propFalloff: 0.62,
    pitchRate: 1.3,
    rollRate: 1.7,
    yawRate: 0.9,
    stability: 1.25,
    gLimit: 3.8,
    airbrakeCd: 0,
    flapsCl: 0.55,
    flapsCd: 0.045,
    gearCd: 0,
    retractableGear: false,
    gearHeight: 1.55,
    groundPitch: 0.02,
    vne: 88,
    chaseDist: 16,
    chaseHeight: 4.2,
    cockpit: { x: 0, y: 1.12, z: -1.0 },
  },
  {
    id: 'islander',
    name: 'ISLANDER BN2T',
    reg: 'G-TRBN',
    role: 'Turbine Utility Twin · STOL',
    blurb:
      'The flying Land Rover. Two turboprops, a slab-sided cabin for nine, and a wing that simply refuses to stop lifting. Off a 300-metre gravel strip with the shopping aboard — all in a day\'s work.',
    engine: 'prop',
    stats: { speed: 0.35, agility: 0.4, handling: 0.9, climb: 0.38 },
    topSpeedKt: 170,
    mass: 2900,
    wingArea: 30.2,
    aspect: 7.4,
    cl0: 0.4,
    clSlope: 5.2,
    stallAoA: 0.31,
    cd0: 0.038,
    maxThrust: 11000,
    propFalloff: 0.55,
    pitchRate: 1.35,
    rollRate: 1.5,
    yawRate: 1.05,
    stability: 1.3,
    gLimit: 3.6,
    airbrakeCd: 0,
    flapsCl: 0.75,
    flapsCd: 0.06,
    gearCd: 0,
    retractableGear: false,
    gearHeight: 1.3,
    groundPitch: 0.01,
    vne: 94,
    chaseDist: 21,
    chaseHeight: 5,
    cockpit: { x: 0, y: 0.78, z: -4.2 },
  },
  {
    id: 'jetranger',
    name: 'BELL 505 JET RANGER X',
    reg: 'N505JR',
    role: 'Light Helicopter',
    blurb:
      'No runway, no problem. A turbine, two seats up front, three in back, and a rotor disc that turns any clearing, rooftop or ridge line into an airport. Collective up gently — she\'ll do the rest.',
    engine: 'heli',
    stats: { speed: 0.28, agility: 0.6, handling: 0.7, climb: 0.42 },
    topSpeedKt: 125,
    mass: 1500,
    wingArea: 99.9, // rotor disc (11.28 m diameter)
    aspect: 1,
    cl0: 0,
    clSlope: 0,
    stallAoA: 1,
    cd0: 0.014, // ×disc = 1.4 m² fuselage flat plate
    maxThrust: 23500,
    propFalloff: 0,
    pitchRate: 1.8,
    rollRate: 2.2,
    yawRate: 1.6,
    stability: 1,
    gLimit: 2.8,
    airbrakeCd: 0,
    flapsCl: 0,
    flapsCd: 0,
    gearCd: 0,
    retractableGear: false,
    gearHeight: 1.32,
    groundPitch: 0,
    vne: 67,
    chaseDist: 17,
    chaseHeight: 4.6,
    cockpit: { x: 0, y: 0.55, z: -1.7 },
  },
  {
    id: 'falcon',
    name: 'FALCON Mk.IV',
    reg: 'G-FLCN',
    role: 'Warbird · Aerobatic',
    blurb:
      'A 1944 thoroughbred with a 1,700-horse V12 up front and absolutely no chill. Rolls like a dream, bites in the stall, and sounds like rolling thunder at full song. Earn it.',
    engine: 'prop',
    stats: { speed: 0.6, agility: 0.85, handling: 0.55, climb: 0.65 },
    topSpeedKt: 380,
    mass: 4150,
    wingArea: 21.8,
    aspect: 5.8,
    cl0: 0.18,
    clSlope: 5.4,
    stallAoA: 0.26,
    cd0: 0.021,
    maxThrust: 16500,
    propFalloff: 0.5,
    pitchRate: 2.3,
    rollRate: 3.4,
    yawRate: 1.1,
    stability: 0.9,
    gLimit: 7,
    airbrakeCd: 0,
    flapsCl: 0.5,
    flapsCd: 0.05,
    gearCd: 0.022,
    retractableGear: true,
    gearHeight: 2.15,
    groundPitch: 0.21,
    vne: 235,
    chaseDist: 19,
    chaseHeight: 4.6,
    cockpit: { x: 0, y: 1.35, z: -0.1 },
  },
  {
    id: 'vector',
    name: 'VECTOR V-25',
    reg: 'AF-225',
    role: 'Multirole Fighter',
    blurb:
      'Twin tails, delta wing, and an afterburner detent that turns the horizon into a suggestion. Supersonic on the deck, 9g in the turn — the fastest way across the map by a country mile.',
    engine: 'jet',
    stats: { speed: 1, agility: 1, handling: 0.4, climb: 1 },
    topSpeedKt: 920,
    mass: 9800,
    wingArea: 38,
    aspect: 3,
    cl0: 0.06,
    clSlope: 3.9,
    stallAoA: 0.42,
    cd0: 0.017,
    maxThrust: 72000,
    afterburner: 1.5,
    propFalloff: 0.12,
    pitchRate: 3.4,
    rollRate: 5.6,
    yawRate: 1,
    stability: 0.75,
    gLimit: 9,
    airbrakeCd: 0.09,
    fbw: true,
    gun: true,
    flapsCl: 0.4,
    flapsCd: 0.04,
    gearCd: 0.025,
    retractableGear: true,
    gearHeight: 2.3,
    groundPitch: 0.04,
    vne: 490,
    chaseDist: 26,
    chaseHeight: 6,
    cockpit: { x: 0, y: 1.1, z: -5.0 },
  },
  {
    id: 'meridian',
    name: 'MERIDIAN 700',
    reg: 'VH-MRD',
    role: 'Executive Jet',
    blurb:
      'Sixteen tonnes of polished composure. She accelerates like a tide and turns like an opinion piece, but holds 430 knots in cruise with champagne-flat manners. Fly her by the numbers.',
    engine: 'jet',
    stats: { speed: 0.75, agility: 0.2, handling: 0.7, climb: 0.55 },
    topSpeedKt: 470,
    mass: 23500,
    wingArea: 74,
    aspect: 8.4,
    cl0: 0.24,
    clSlope: 5.6,
    stallAoA: 0.24,
    cd0: 0.02,
    maxThrust: 96000,
    propFalloff: 0.18,
    pitchRate: 0.95,
    rollRate: 1.25,
    yawRate: 0.7,
    stability: 1.35,
    gLimit: 2.6,
    airbrakeCd: 0.07,
    flapsCl: 0.7,
    flapsCd: 0.06,
    gearCd: 0.02,
    retractableGear: true,
    gearHeight: 3.75,
    groundPitch: 0.01,
    vne: 250,
    chaseDist: 48,
    chaseHeight: 11,
    cockpit: { x: 0, y: 2.4, z: -12.4 },
  },
];

export const specById = (id: string): AircraftSpec =>
  CATALOG.find((s) => s.id === id) ?? CATALOG[0];
